language: ruby 
install:
  - make
  - make install
script: make test
branches:
  only:
    - master
notifications:
  recipients:
    - dev@sekati.com
  email:
    on_success: change
    on_failure: always
