language: ruby 
install:
  - make
  - make install
before_script: /usr/local/bin/actionserverctl start
script: make test
after_script: /usr/local/bin/actionserverctl stop
branches:
  only:
    - master
notifications:
  recipients:
    - dev@sekati.com
  email:
    on_success: change
    on_failure: always
